services:
  palvelin:
    build: ./Palvelin
    container_name: palvelin
    volumes:
      - servervol:/serverdata
    ports:
      - 8000:8000
    networks:
      - verkko
    environment:
      - DATA_DIR=/serverdata
      - PORT=8000
      - PYTHONUNBUFFERED=1
  asiakas:
    build: ./Asiakas
    container_name: asiakas
    volumes:
      - clientvol:/clientdata
    networks:
      - verkko
    environment:
      - DATA_DIR=/clientdata
      - SERVER_ADDRESS:http://palvelin:8000
      - PYTHONUNBUFFERED=1
    depends_on:
      - palvelin

volumes:
  servervol:
  clientvol:

networks:
  verkko: