services:
  palvelin:
    build: ./Palvelin
    ports:
      - "8000:8000"
    volumes:
      - servervol:/app/dataa
    networks:
      - verkko
    environment:
      - DATA_DIR=/app/dataa
  asiakas:
    build: ./Asiakas
    volumes:
      - clientvol:/clientdata
    networks:
      - verkko
    environment:
      - DATA_DIR=/clientdata

volumes:
  servervol:
    driver: local
  clientvol:
    driver: local

networks:
  verkko:
    driver: bridge